"""create_initial_schema

Revision ID: 012057fd82c0
Revises: 
Create Date: 2026-08-29 11:48:58.001145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '012057fd82c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dead_letter_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('razorpay_key_id', sa.String(), nullable=True),
    sa.Column('razorpay_key_secret', sa.String(), nullable=True),
    sa.Column('amount_threshold', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbox_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('aggregate_id', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('google_subject_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_google_subject_id'), 'users', ['google_subject_id'], unique=True)
    op.create_table('webhook_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider_event_id', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_event_id')
    )
    op.create_table('customers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('payment_history_success_rate', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_table('merchant_recovery_policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('retry_backoff', sa.Integer(), nullable=True),
    sa.Column('amount_threshold', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('allowed_actions', sa.JSON(), nullable=True),
    sa.Column('human_review_threshold', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('risk_threshold', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cooldown', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=True),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('failure_code', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('provider_event_id', sa.String(), nullable=True),
    sa.Column('payload_metadata', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_event_id')
    )
    op.create_table('recovery_cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=True),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('IDENTIFIED', 'DETECTED', 'ANALYZING', 'ACTION_PROPOSED', 'GUARD_REVIEW', 'APPROVED', 'EXECUTING', 'RECOVERED', 'FAILED', 'BLOCKED', 'HUMAN_REVIEW', 'CLOSED', name='casestatus'), nullable=True),
    sa.Column('priority_score', sa.Integer(), nullable=True),
    sa.Column('expected_recovery_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('current_recovery_attempt', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('next_action_at', sa.DateTime(), nullable=True),
    sa.Column('audit_log', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('policy_id', sa.String(), nullable=True),
    sa.Column('policy_version', sa.Integer(), nullable=True),
    sa.Column('experiment_group', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['payment_events.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['merchant_recovery_policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recovery_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.Enum('RETRY_PAYMENT', 'SEND_PAYMENT_REMINDER', 'SEND_CHECKOUT_RECOVERY_MESSAGE', 'RETRY_SUBSCRIPTION', 'SEND_INVOICE_REMINDER', 'ESCALATE_TO_HUMAN', 'DO_NOTHING', name='actiontype'), nullable=False),
    sa.Column('proposed_by', sa.String(), nullable=False),
    sa.Column('state', sa.Enum('PROPOSED', 'APPROVED_BY_GUARD', 'REJECTED_BY_GUARD', 'EXECUTED', 'FAILED', 'SUCCESSFUL', name='actionstate'), nullable=True),
    sa.Column('authorization_token', sa.String(), nullable=True),
    sa.Column('action_id', sa.String(), nullable=True),
    sa.Column('execution_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_id')
    )
    op.create_table('ai_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('action_id', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('strategy_version', sa.String(), nullable=False),
    sa.Column('playbook_version', sa.String(), nullable=False),
    sa.Column('input_context_hash', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('proposal', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['recovery_actions.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('action_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('decision_source', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['recovery_actions.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('executions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('action_id', sa.String(), nullable=True),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('provider_reference', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reconciled_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('result_code', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['recovery_actions.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_reference')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('executions')
    op.drop_table('audit_events')
    op.drop_table('ai_decisions')
    op.drop_table('recovery_actions')
    op.drop_table('recovery_cases')
    op.drop_table('payment_events')
    op.drop_table('merchant_recovery_policies')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_users_google_subject_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('outbox_events')
    op.drop_table('merchants')
    op.drop_table('dead_letter_jobs')
    # ### end Alembic commands ###
